### API Requests for Testing ###

#### User Authentication ####
@TOKEN = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImVtYWlsIjoiam9obi5kb2VAZXhhbXBsZS5jb20iLCJyb2xlIjoiYWlkX3JlY2lwaWVudCIsImlhdCI6MTcyODIxMzUxNywiZXhwIjoxNzI4MjIwNzE3fQ.U4xJVQxmb9hw0PepcicPm3ZF-FdDvc00QP1HNPx15y8
##### Register User #####
POST http://localhost:3000/auth/register
Content-Type: application/json

{
  "id":1,
  "name": "John Doe",
  "email": "john.doe@example.com",
  "phone": "1234567890",
  "password": "Password123",
  "role": "aid_recipient"
}

##### Login User #####
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "email": "john.doe@example.com",
  "password": "Password123"
}

#### Aid Requests ####

##### Get All Aid Requests #####
GET http://localhost:3000/aidrequests
Authorization: Bearer {{TOKEN}}

##### Get One Aid Requests #####
GET http://localhost:3000/aidrequests/1
Authorization: Bearer {{TOKEN}}


##### Create Aid Request #####
POST http://localhost:3000/aidrequests
Authorization: Bearer {{TOKEN}}
Content-Type: application/json

{
  "userId": 2,
  "type": "Food Assistance",
  "description": "Need food for a family of four"
}

#### Organizations ####

##### Get All Organizations #####
GET http://localhost:3000/organizations
Authorization: Bearer {{TOKEN}}
##### Create Organization #####
POST http://localhost:3000/organizations
Authorization: Bearer {{TOKEN}}
Content-Type: application/json

{
  "name": "TURDES",
  "address": "123 Main",
  "contactInfo": "turdes@app.org"
}