### API Requests for Testing ###

#### User Authentication ####
@TOKEN = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImVtYWlsIjoiam9obi5kb2VAZXhhbXBsZS5jb20iLCJyb2xlIjoiYWlkX3JlY2lwaWVudCIsImlhdCI6MTcyODI4NDcwMywiZXhwIjoxNzI4Mjg1NjAzfQ.dP5QAHzlvLp4i7XfliXUFQDB6FEcLiASsu_z7ixIuUo
@refreshToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImVtYWlsIjoiam9obi5kb2VAZXhhbXBsZS5jb20iLCJyb2xlIjoiYWlkX3JlY2lwaWVudCIsImlhdCI6MTcyODIxODE5MSwiZXhwIjoxNzI4ODIyOTkxfQ.5S1SQBEaiTiZ0WmY9JTVhEjdv-cJdMn-ADHu0N--8kc
##### Register User #####
POST http://localhost:3000/auth/register
Content-Type: application/json

{
  "id":1,
  "name": "John Doe",
  "email": "john.doe@example.com",
  "phone": "1234567890",
  "password": "Password123",
  "role": "aid_recipient"
}

##### Login User #####
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "email": "john.doe@example.com",
  "password": "Password123"
}

###refresh token ###
POST http://localhost:3000/auth/refresh
Content-Type: application/json

{
  "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImVtYWlsIjoiam9obi5kb2VAZXhhbXBsZS5jb20iLCJyb2xlIjoiYWlkX3JlY2lwaWVudCIsImlhdCI6MTcyODIzMjg0MywiZXhwIjoxNzI4ODM3NjQzfQ.bFjM6MyAuZIlPi0VjNongdaXQf4AX1tQffRvcZUfjvM"
}

#### Aid Requests ####

##### Get All Aid Requests #####
GET http://localhost:3000/aidrequests
Authorization: Bearer {{TOKEN}}

##### Get One Aid Requests #####
GET http://localhost:3000/aidrequests/1
Authorization: Bearer {{TOKEN}}


##### Create Aid Request #####
POST http://localhost:3000/aidrequests
Authorization: Bearer {{TOKEN}}
Content-Type: application/json

{
  "userId": 2,
  "type": "Food Assistance",
  "description": "Need food for a family of four"
}

#### Organizations ####

##### Get All Organizations #####
GET http://localhost:3000/organizations
Authorization: Bearer {{TOKEN}}
##### Create Organization #####
POST http://localhost:3000/organizations
Authorization: Bearer {{TOKEN}}
Content-Type: application/json

{
  "name": "TURDES",
  "address": "123 Main",
  "contactInfo": "turdes@app.org"
}